resource_management:
 runner_config:
   job_setup_timeout_minutes: 60
   job_execution_timeout_minutes: 60
   pr_job_setup_timeout_minutes: 60
   pr_job_execution_timeout_minutes: 60
license-compliance:
  deny_list:
    - Apache*
    - MIT
