applications:
- api_domain: new.juice-shop.herokuapp.com
  application_name: some-app-two
  authentication_key: password
  authentication_mode: selenium
  authentication_value: ${{ jit_secrets.some-app_web }}
  exclude_paths: []
  login_page_url: https://juice-shop.herokuapp.ssscom/#/loginasdaj
  password: encrypted$AQICAHi8oKBeWufpQyBhS/I7j+xeXOszTLo37NZpVZLtG7GGBQEkfcDQGv3JqOP5dB+bPgiEAAAAZDBiBgkqhkiG9w0BBwagVTBTAgEAME4GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcCsoIIvIDX1NSYOdAgEQgCFeUZEqhzPCd8zg3egIX8vrV6uqUw2PWPdqTdCpVVZfilU=
  password_css_selector: ''
  password_ref: ${{ jit_secrets.web_scan_password }}
  target_url: https://juice-shop.herokuapp.com
  type: web
  username: username
  username_css_selector: ''
- api_domain: juice-shop.herokuapp.com
  application_name: some-appnew
  authentication_key: password
  authentication_mode: selenium
  authentication_value: ${{ jit_secrets.some-app_web }}
  exclude_paths: []
  login_page_url: https://juice-shop.herokuapp.com/#/login
  password: encrypted$AQICAHi8oKBeWufpQyBhS/I7j+xeXOszTLo37NZpVZLtG7GGBQEkfcDQGv3JqOP5dB+bPgiEAAAAZDBiBgkqhkiG9w0BBwagVTBTAgEAME4GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcCsoIIvIDX1NSYOdAgEQgCFeUZEqhzPCd8zg3egIX8vrV6uqUw2PWPdqTdCpVVZfilU=
  password_css_selector: ''
  password_ref: ${{ jit_secrets.web_scan_password }}
  target_url: https://juice-shop.herokuapp.com
  type: web
  username: username
  username_css_selector: ''
- api_domain: some.api.com
  application_name: test-liron-latest
  authentication_key: Authorization
  authentication_mode: header-bearer
  authentication_value: ${{ jit_secrets.test-liron-latest_web }}
  exclude_paths: []
  target_url: https://juice-shop.herokuapp.com
  type: web
- api_domain: custom.api
  application_name: custom-header-app
  authentication_key: Bearer
  authentication_mode: header-custom
  authentication_value: ${{ jit_secrets.custom-header-app_web }}
  exclude_paths: []
  target_url: https://juice-shop.herokuapp.com
  type: web
- api_domain: test.api
  application_name: defender
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: .jit/RealityDefenderAPI_openapi.json
  type: api
- api_domain: test.api
  application_name: open
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: .jit/openapi.json
  type: api
