applications:
- api_domain: juice-shop.herokuapp.com
  application_name: some-app
  authentication_key: password
  authentication_mode: selenium
  authentication_value: ${{ jit_secrets.some-app_web }}
  exclude_paths: []
  login_page_url: https://juice-shop.herokuapp.com/#/login
  password: encrypted$AQICAHi8oKBeWufpQyBhS/I7j+xeXOszTLo37NZpVZLtG7GGBQEkfcDQGv3JqOP5dB+bPgiEAAAAZDBiBgkqhkiG9w0BBwagVTBTAgEAME4GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcCsoIIvIDX1NSYOdAgEQgCFeUZEqhzPCd8zg3egIX8vrV6uqUw2PWPdqTdCpVVZfilU=
  password_css_selector: ''
  target_url: https://juice-shop.herokuapp.com
  type: web
  username: username
  username_css_selector: ''
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
license-compliance:
  dual_license: permissive
resource_management:
  runner_config:
    job_execution_timeout_minutes: 3
    job_setup_timeout_minutes: 3
    pr_job_execution_timeout_minutes: 3
    pr_job_setup_timeout_minutes: 3
