github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
resource_management:
 runner_config:
   job_setup_timeout_minutes: 3
   job_execution_timeout_minutes: 3
   pr_job_setup_timeout_minutes: 3
   pr_job_execution_timeout_minutes: 3
license-compliance:
  dual_license: permissive
